// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBhgWNxbaHcREhzrWCbP4h3cDhZ5dvFo',
    appId: '1:27541718356:web:62d8aba70258d5bf2374c1',
    messagingSenderId: '27541718356',
    projectId: 'flixlist-a7e97',
    authDomain: 'flixlist-a7e97.firebaseapp.com',
    storageBucket: 'flixlist-a7e97.appspot.com',
    measurementId: 'G-3PLDDKXBDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNzyN3-ywa2bLkYvGgxBeqH8p5z9RT_k',
    appId: '1:27541718356:android:9e213ab21a6f6ab92374c1',
    messagingSenderId: '27541718356',
    projectId: 'flixlist-a7e97',
    storageBucket: 'flixlist-a7e97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxlkaKOxrU7BAOw8OwgnKuxWsw5h2Kvo',
    appId: '1:27541718356:ios:17d6e13dd59574322374c1',
    messagingSenderId: '27541718356',
    projectId: 'flixlist-a7e97',
    storageBucket: 'flixlist-a7e97.appspot.com',
    iosClientId: '27541718356-n9lo3ta7e3qheq29un0u1t735u2lp75s.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flixlist',
  );
}
